### ISSUE TITLE
Create a CI for all the courses

### ISSUE THREAD

**Issue by BWhannou** [ML-for-B-E/.github#2]
**Description**: the goal is to standardize the main branch to a high level of quality

**Suggested implementation**: 
1. check that the repository contains the following folders: notebooks, figures, requirements, src, tests, .gitignore, README.md, setup.py
2. check that all the tests run (functions and notebooks)
3. check that the code is 3.8 compatible
4. check that there is no .csv (we will implement a proper way to load data using Dropbox), .png (except in the folder figures)
5. check `black` compatibility

**Comment by akouete-kpakpo** [comment]
> check that there is no .csv (we will implement a proper way to **load data using Dropbox**), .png (except in the folder figures)

thanks @BWhannou . For the point 4, let's get rid of Dropbox. We'll see how to use a bucket from a Cloud provider (GCP or Amazon)

**Comment by akouete-kpakpo** [comment]
## Tasks 

- [ ] implement the CI in https://github.com/ML-for-B-E/decision_tree_course
- [ ] refactor the utils for CI  and tests in a repo
- [ ] deploy the refactor version in all repos of the project
